### ISSUE TITLE
Implement a Script to create Train and Test Sets for our Dataset

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Malaria-Detection#10]
## AIM

Implement a Script to create Train and Test Sets for our Dataset

## Details

- Download the [Kaggle Dataset](https://www.kaggle.com/iarunava/cell-images-for-detecting-malaria)
- Load the Images from the Disk and scale them.
- Assign Binary Values to them and dump them to save Pre-Processing Time every time we load the Dataset.
- Split the Dataset into Training and Testing Sets.

**Comment by Bijay555** [comment]
@HarshCasper can I use pickle to dump?

**Comment by jyrj** [comment]
@HarshCasper I would like to work on this

**Comment by HarshCasper** [comment]
Yes @Bijay555 

I am assigning in to you @Bijay555 

@jyrj Issues are assigned on "First Come, First Serve" basis. I will create more Issues in the future nonetheless
