### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by spiyush0212** [HarshCasper/Malaria-Detection#2]
Hello, I am trying to set up this project on my PC. I have cloned it and also installed Python, Pip, NumPy but when I do "pip install -r requirements.txt". I get an error message;

$ pip install tensorflow==1.13.1
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.13.1

Can you please tell me how to proceed?

My installed versions of ;
Python 3.8.3
NumPy 1.18.5
pip 20.2.1

I even tried downloading TensorFlow 2.3.0 but then still I had the error and I could not downgrade it to TF 1.13.1 so eventually, I uninstalled it completely. So how should I proceed?

**Comment by HarshCasper** [comment]
Hello @spiyush0212 

You can install a Virtual Environment first and here is a [tutorial](https://www.geeksforgeeks.org/creating-python-virtual-environment-windows-linux/) for the same.

**Comment by spiyush0212** [comment]
Thank you! I will try to do this now :)

**Comment by ghimireadarsh** [comment]
The issue you are facing is because of the Python3.8, since python3.8 doesn't have support for tensorflow 1, so try using python <3.8.
