### ISSUE TITLE
UI Improvements 

### ISSUE THREAD

**Issue by spiyush0212** [HarshCasper/Malaria-Detection#3]
![Screenshot (496)](https://user-images.githubusercontent.com/54810697/89723010-a2908900-da0e-11ea-9a6e-c6bee5461f9c.png)

## In the attached image, I have tried to update the UI of the default index.html page. 
# Some of the changes that I have made;

* 1) Shifted the inline CSS to a new CSS document
* 2) Removed the borders from all the divs
* 3) Changed the colour of "display-2" to "bootstrap-danger"
* 4) Added "btn-success" class to the "Submit" button.
* 5) Added alt text for the "disease.png" 

## Please let me know how to proceed further on this now :)

**Comment by HarshCasper** [comment]
Hello @spiyush0212 

I guess that you are making the changes for `HakinCodes Contributor's Hack 2020`. If so, we will start this project from scratch for a better learning curve up here on an [empty repository](https://github.com/HakinCodes/Malaria-Detection). To get started, we can make use of this UI before we proceed with the final implementation of a better UI.

**Comment by spiyush0212** [comment]
Okay @HarshCasper 
I understand it now :) and will defiantly work on the newer repo for the Hack'2020
Thank you!
